### ISSUE TITLE
vcvarsall error

### ISSUE THREAD

**Issue by OzgunKB** [youngquan/goldenmask#1]
`goldenmask -i -l 2 level1.py

Compiling level1.py because it changed.

[1/1] Cythonizing level1.py

running build_ext

building 'level1' extension

error: Unable to find vcvarsall.bat`

**Comment by youngquan** [comment]
Thanks for feedback.
Are you on Windows? If so, here are some tips from the offical docs of [Cython:](https://cython.readthedocs.io/en/latest/src/quickstart/install.html)
> Unlike most Python software, Cython requires a C compiler to be present on the system. The details of getting a C compiler varies according to the system used:
> - Windows A popular option is to use the open source MinGW (a Windows distribution of gcc). See the appendix for instructions for setting up MinGW manually. Enthought Canopy and Python(x,y) bundle MinGW, but some of the configuration steps in the appendix might still be necessary. Another option is to use Microsoft’s Visual C. One must then use the same version which the installed Python was compiled with.

You have to install the Micorsoft's Visual C or MinGW. You can find detailed description at:

- https://cython.readthedocs.io/en/latest/src/tutorial/appendix.html
- https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
